[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_ENV = "production" }

[build.environment]
  NODE_VERSION = "14.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
